server:
  port: 9000

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/kojnexus_oauth2?useSSL=false"
    username: "root"
    password: "@Localhost2024"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE